version: '3.9'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://portfolio-db:3306/portf
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=vamsi@2004/01/02
    depends_on:
      - portfolio-db

  portfolio-db:
    image: mysql:8.0.41
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vamsi@2004/01/02
      MYSQL_DATABASE: portf
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: